name: scholarship_trading_app
description: "Scholars  # Notifications
  flutter_local_notifications: ^15.1.3p Marketplace App - Buy, Sell, and Auction Scholarships"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  
  # Payment Processing
  flutter_stripe: ^10.1.1
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^12.1.3
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  
  # Image & File Handling
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  cached_network_image: ^3.3.1
  
  # UI Components
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  
  # Notifications
  
  # Charts & Reports
  fl_chart: ^0.66.2
  pdf: ^3.10.7
  
  # Date & Time
  table_calendar: ^3.0.9
  
  # Chat functionality
  bubble: ^1.2.1
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Google Sign In - Temporarily disabled
  # google_sign_in: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
